import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <main className="min-h-screen w-full dark:bg-gray-800">
            <Header />
            <div className="max-w-screen-2xl mx-auto p-5 lg:py-8">
              {children}
            </div>
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
